config/routes.rb
Rails.application.routes.draw do
  ActiveAdmin.routes(self)
  devise_for :users, controllers: {registrations: "users/registrations"}

  get :search, to: 'search#index'
  get :contact, to: 'pages#contact'
  scope "(:locale)" do
    get 'pages/home'

    resources :categories, only: [:show, :index] do
      resources :contents do
        resources :documents, only: [:destroy, :create]
      end
    end

    root 'pages#home'
  end

  get '/:locale' => 'categories#index'
end

app/models/category.rb
class Category < ActiveRecord::Base
  validates :slug, presence: true
  validates :slug, length: { maximum: 255 }
  has_many :contents

  SLUGS = [
    "eventos",
    "inovacoes",
    "comunidade",
    "especificacoes",
    "editora",
    "noticias",
    "literatura",
    "padronizacao",
    "treinamentos",
    "o-certo-e-o-errado",
    "mercado-saneamento",
    "wdb-mercado-saneamento"
  ].freeze

  def name
    I18n.t("categories.name.#{self.slug}")
  end

  class << self

    def create_defaults!
      SLUGS.each do |slug|
        self.find_or_initialize_by(slug: slug).save!
      end
    end

  end
end

app/models/content.rb
class Content < ActiveRecord::Base
  validates :title, :locale, :category, presence: true
  validates :title, :locale, length: { maximum: 255 }
  belongs_to :category
  has_many :documents, dependent: :destroy

  default_scope -> { where(locale: I18n.locale) }

  def self.search(q)
    includes(:category).where("unaccent(title) ILIKE unaccent(?)", "%#{q}%")
  end
end

app/models/document.rb
class Document < ActiveRecord::Base
  has_attached_file :file
  validates_attachment_content_type :file, :content_type => /\A.*\Z/
  validates :content, presence: true
  belongs_to :content

  def file_direct_url=(value)
    open(value, ssl_verify_mode: OpenSSL::SSL::VERIFY_NONE) do |file|
      self.attributes = {
        file: file,
        file_file_name: File.basename(value),
      }
    end
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  after_commit :send_admin_email, on: :create
  before_validation  :set_expiration_date
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  validates :name, :email, :expiration_date, presence: true
  validates :email, uniqueness: true

  enum position: [:director, :adviser, :manager, :supervisor, :operational]
  AREA_INTERESTS = [:supply, :sewage, :drainage, :residue, :management]

  private
  def send_admin_email
    NewUserWorker.perform_async(self.id)
  end

  def set_expiration_date
    self.expiration_date ||= 7.days.from_now
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  ensure_security_headers # See more: https://github.com/twitter/secureheaders
  before_action :set_locale
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :user_expired
  before_action :user_blocked

  helper_method :is_admin?

  def default_url_options(options={})
    { :locale => ((I18n.locale == I18n.default_locale) ? nil : I18n.locale) }
  end

  def set_locale
    I18n.locale = params[:locale] || I18n.default_locale
  end

  def is_admin?
    current_user.is_admin?
  end

  def ensure_admin!
    redirect_to(root_path, notice: I18n.t('application.ensure_admin')) unless is_admin?
  end

  def authenticate_admin_user!
    unless user_signed_in? && current_user.is_admin?
      redirect_to(root_url, notice: 'Apenas para administradores...')
    end
  end

  def configure_permitted_parameters
      devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:name, :email, :password, :password_confirmation, :phone, :company, :position, area_interest: []) }
      devise_parameter_sanitizer.for(:account_update) { |u| u.permit(:name, :email, :password, :password_confirmation, :phone, :company, :position, area_interest: []) }
  end

  def user_expired
    if user_signed_in? && current_user.expiration_date < Time.now.to_date && !current_user.is_admin?
      flash[:notice] = I18n.t('application.account_expired')
      sign_out current_user
    end
  end

  def user_blocked
    if user_signed_in? && current_user.blocked?
      flash[:notice] = I18n.t('application.account_blocked')
      sign_out current_user
    end
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_filter :authenticate_user!

  def index
    @categories = Category.order(:position)
  end
end

app/controllers/contents_controller.rb
class ContentsController < ApplicationController
  before_filter :authenticate_user!

  before_action :ensure_admin!, only: [:new, :edit, :update, :create, :destroy]
  before_action :set_content, only: [:show, :edit, :update, :destroy]
  before_action :set_category

  def index
    @contents = Content.where(category_id: params[:category_id]).order("created_at DESC")
  end

  def show
  end

  def new
    @content = Content.new
  end

  def edit
  end

  def create
    @content = Content.new(content_params)
    @content.category = @category

    respond_to do |format|
      if @content.save
        format.html { redirect_to [@category, @content], notice: 'Content was successfully created.' }
        format.json { render :show, status: :created, location: @content }
      else
        format.html { render :new }
        format.json { render json: @content.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @content.update(content_params)
        format.html { redirect_to [@category, @content], notice: 'Content was successfully updated.' }
        format.json { render :show, status: :ok, location: @content }
      else
        format.html { render :edit }
        format.json { render json: @content.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @content.destroy
    respond_to do |format|
      format.html { redirect_to [@category, :contents], notice: 'Content was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_content
      @content = Content.find(params[:id])
    end

    def set_category
      @category = Category.find(params[:category_id])
    end

    def content_params
      params.require(:content).permit(:title, :description, :category_id, :premium)
    end
end

app/controllers/documents_controller.rb
class DocumentsController < ApplicationController
  before_filter :authenticate_user!
  before_action :set_category

  def create
    @content = Content.find(params[:content_id])
    @document = Document.new(document_params)
    @document.content = @content

    respond_to do |format|
      if @document.save
        format.html { redirect_to [@category, @content], notice: 'Document was successfully created.' }
        format.json { render :show, status: :created, location: @document }
      else
        format.html { redirect_to [@category, @content] }
        format.json { render json: @document.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @content = Content.find(params[:content_id])
    @document = Document.find(params[:id])
    @document.destroy
    respond_to do |format|
      format.html { redirect_to [@category, @content], notice: 'Document was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def document_params
      params.require(:document).permit(:file, :file_direct_url)
    end

    def set_category
      @category = Category.find(params[:category_id]) if params[:category_id].present?
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  
  def contact
  end

  def home
    if user_signed_in?
      redirect_to categories_path if user_signed_in?
    else
      render layout: "landing"
    end
  end
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  before_action :authenticate_user!

  def index
    @contents = Content.search(params[:q])
  end
end

app/controllers/users/registrations_controller.rb
class  Users::RegistrationsController < Devise::RegistrationsController

  protected

  def update_resource(resource, params)
    resource.update_without_password(params)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/user_helper.rb
module UserHelper

 def position_collection
   result = {}
   User.positions.keys.each { |k| result.merge!(I18n.t("users.position.#{k}") => k) }
   result
 end

 def area_interest_collection
  User::AREA_INTERESTS.map { |k| I18n.t("users.area_interest.#{k}") }
 end
end

app/views/application/_flash_messages.html.slim
section.flash-notice
  .wrapper
    - flash.each do |key, value|
      div id="flash_#{key}"
        = value

app/views/application/_footer.html.slim
footer
  hr.waves-primary

  .wrapper
    small = t('.contact')
    h4 = t('.feedback')
    p  
      = t('.contact_head')
      a href=contact_path #{t('.contact_link')}
      = t('.contact_email')

app/views/application/_header.html.slim
header
  .wrapper
    h1.logo
      = link_to image_tag("waterdb-logo.svg" ,class: "menu_icon"), root_path

    nav
      - if user_signed_in?
        ul.user-nav-list
          li
            = render 'search'
          li
            p = current_user.name
          li.menu-top
            = image_tag("icons/icon-menu.svg", width: "20", heigh:"auto" ,class: "menu_icon")
            ul.user-nav-secondary
              li
                = link_to 'Home', root_path, id: "home"
              li
                = link_to t('.my_account'), edit_user_registration_path, id: "home"
              li
                = link_to t('.logout'), destroy_user_session_path, method: :delete, id: "sign_out"
              li
                - if I18n.locale == :"pt-BR"
                  = link_to t('.es_version'), root_path(locale: :es)
                - else
                  = link_to t('.ptbr_version'), root_path(locale: nil)
      - else
        ul.user-nav-list
          li
            = link_to t('.login'), new_user_session_path, id: "sign_in"

app/views/application/_search.html.slim
= simple_form_for '', url: search_path, method: :get, html: { class: 'search-header' } do |f|
  = f.input :q, placeholder: 'Busca', label: false,
    input_html: { value: params[:q].is_a?(String) ? params[:q] : '' }

app/views/categories/index.html.slim
hr.down-waves

section.dashboard
  .wrapper
    ul.dashboard-list
      - @categories.each do |category|
        li
          .icon
            = link_to image_tag("icons/icon-#{category.slug}.svg" ,class: "dashboard-icon", id: "dashboard-#{category.slug}"), [category, :contents]
          = link_to category.name, [category, :contents]

app/views/contents/_document_js_tmpl.html.erb
<div style="display:none;">
  <script id="s3ff_template" type="text/x-tmpl">
    {^{if failReason}}
      <div class="progress s3ff_progress">
        <div class="progress-bar progress-bar-danger s3ff_bar" style="width:80%;">
          <span class="fa fa-exclamation-triangle"></span>
          {^{:failReason}}
        </div>
      </div>
    {^{else}}
      <div class="progress s3ff_progress" style="display:none;">
        <div class="progress-bar progress-bar-striped active s3ff_bar" style="width:0%;"></div>
      </div>
    {{/if}}
    {^{if result}}
      <div class="thumbnail" id="upload-{{:unique_id}}">
        <input type="hidden" data-link="name{:fieldname} value:{:result.url}"/>
        {^{if placeholder}}
          <img data-link="src{:result.url} alt{:result.filename}">
        {{/if}}
        <div class="caption">
          <span class="fa fa-file-o"></span>
          {^{:result.filename}}
          <button class="close button alert" data-dismiss="alert" data-unique_id="{{:unique_id}}" data-target="#upload-{{:unique_id}}" style="margin-left:1em;" type="button">
            <span class="sr-only"><%= t('.remove') %></span>
          </button>
        </div>
      </div>
    {^{else}}
      {^{if placeholder}}
        <div class="thumbnail" id="upload-{{:unique_id}}">
          {^{if placeholder.url}}
            <img data-link="src{:placeholder.url}">
          {{/if}}
          {^{if placeholder.filename}}
            <div class="caption">
              <span class="fa fa-file-o"></span>
              {^{:placeholder.filename}}
            </div>
          {{/if}}
        </div>
      {{/if}}
    {{/if}}
  </script>
</div>

app/views/contents/_form.html.slim
= simple_form_for([@category, @content]) do |f|
  = f.error_notification

  .form-inputs
    = f.input :title
    = f.input :description
    = f.input :premium

    = f.button :submit

app/views/contents/edit.html.slim
section.headline
  .wrapper
    .icon-wrapper
      .icon
        = image_tag("icons/icon-#{@category.slug}.svg" ,class: "dashboard-icon")
    h1 = @category.name

section.content-primary
  .wrapper
    .content-box
      article
        h1 = t('.title')
        hr.waves-secondary 

        == render 'form'

    .content-footer
      = link_to t('.back'),  [@category, @content]

app/views/contents/index.html.slim
section.headline
  .wrapper
    .icon-wrapper
      .icon
        = image_tag("icons/icon-#{@category.slug}.svg" ,class: "dashboard-icon")
    h1 = @category.name

section.content-primary
  .wrapper
    - if @contents.any?
      ul.content-list
        - @contents.each do |content|
          li.content-box
            article
              h2 = link_to truncate(content.title, length: 80), [@category, content]
              hr.waves-secondary
              p
                = truncate(content.description, length: 140)

              ul.content-actions-list
                li = link_to t('contents.index.edit'), [:edit, @category, content] if is_admin?
                li = link_to t('contents.index.destroy'), [@category, content], data: {:confirm => t('contents.index.confirm')}, :method => :delete if is_admin?

            .content-footer
              .attachment
                .icon = content.documents.size
              .attachment-label
                label= "#{t('contents.index.attachments')} #{'(premium)' if content.premium?}"
                = link_to t('.show'), [@category, content]
    - else
      h2 Ooops!
      h4 = t('.category_without_content')
      hr.waves-secondary
      p
        = t('.suggestions')
        br
        = t('.send_email')
        br
        = link_to t('.back'), root_path

  .wrapper
    = link_to t('contents.index.new'), new_category_content_path(@category), :class => 'button' if is_admin?

app/views/contents/new.html.slim
section.headline
  .wrapper
    .icon-wrapper
      .icon
        = image_tag("icons/icon-#{@category.slug}.svg" ,class: "dashboard-icon")
    h1 = @category.name

section.content-primary
  .wrapper
    .content-box
      article
        h1 = t('.title')
        hr.waves-secondary

        == render 'form'

    .content-footer
      = link_to t('.back'), [@category, :contents]

app/views/contents/show.html.slim
section.headline
  .wrapper
    .icon-wrapper
      .icon
        = image_tag("icons/icon-#{@category.slug}.svg" ,class: "dashboard-icon")
    h1 = link_to @category.name, [@category, :contents], class: 'back-category'

section.content-primary
  .wrapper
    .content-box
      article
        big = @content.category.name
        h2 = @content.title

        hr.waves-secondary
        p
          = @content.description

        ul.content-actions-list
          li = link_to t('.edit'), [:edit, @category, @content] if is_admin?
          li = link_to t('.back'), [@category, :contents]

        = render partial: "document_js_tmpl"

      .content-footer
        ul.attachment-list
          - @content.documents.each do |document|
            li
              .attachment
                .icon
                  = image_tag("icons/icon-attachment.svg" ,class: "dashboard-icon")

              label = document.file_file_name

              .actions
                = link_to t('.download'), document.file.url, target: :_blank
                = link_to t('.remove'), [@category, @content, document], method: :delete, data: { confirm: t('.confirm') }, :class => 'button alert' if is_admin?
          - if is_admin?
            li
              h3 = t('.choose_files')
              = form_for [@category, @content, Document.new], :html => {:class => 'form-attachment'} do |f|
                .file-wrapper
                  = f.s3_file_field :file, required: true
                = f.submit t('.save_attachment')

app/views/layouts/application.html.slim
doctype 5
html lang=I18n.locale
  head
    meta charset="utf-8"
    meta name="keywords" content=""
    meta name="description" content=""

    title
      = page_title(app_name: 'WaterDB')

    link href="/favicon.ico" rel=("shortcut icon")

    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags

    /![if lt IE 9]
      script src="http://html5shim.googlecode.com/svn/trunk/html5.js"

  body class=body_class
    = render 'flash_messages'
    = render 'header'
    = yield
    = render 'footer'

  javascript:
    (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
    (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
    m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
    })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

    ga('create', 'UA-57362715-1', 'auto');
    ga('send', 'pageview');

app/views/layouts/landing.html.slim
doctype 5
html lang=I18n.locale
  head
    meta charset="utf-8"
    meta name="keywords" content=""
    meta name="description" content=""

    title
      = page_title(app_name: 'WaterDB')

    link href="/favicon.ico" rel=("shortcut icon")

    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags

    /![if lt IE 9]
      script src="http://html5shim.googlecode.com/svn/trunk/html5.js"

  body#body-landing class=body_class
    = render 'flash_messages'
    = yield

  javascript:
    (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
    (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
    m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
    })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

    ga('create', 'UA-57362715-1', 'auto');
    ga('send', 'pageview');

app/views/pages/contact.html.slim
.wraper
  .contact-form
    iframe allowtransparency="true" frameborder="0" height="557" scrolling="no" src="https://waterdb.wufoo.com/embed/z1nfob580qs7zzr/" style="width:100%;border:none"

app/views/pages/home.html.slim
section.landing-primary
  .wrapper
    .translation-link
      - if I18n.locale == :"pt-BR"
        = link_to t('.es_version'), root_path(locale: :es)
      - else
        = link_to t('.ptbr_version'), root_path(locale: nil)
    = image_tag("waterdb-logo.svg", width: "300", heigh:"auto" ,class: "landing_icon")

    h1 = t('.title')
    
    p.sign-up-links
      = link_to t('.login'), new_user_session_path, id: "sign_in", class:"button"
      span ou
      = link_to t('.sign_up'), new_user_registration_path, class: "button"

section.landing-secondary
  .wrapper
    hr.waves-primary

    p = t('.features')
    p = t('.join_us')

    small 
      = t('.expiration_warning')
      a href=contact_path #{t('.expiration_warning_link')}
      = t('.expiration_warning_email')

footer.landing-footer
  section.landing-footer-primary
    .wrapper
      hr.waves-tertiary

      = image_tag("gph-categories.svg", width: "450", heigh:"auto" ,class: "landing_icon")

  section.landing-footer-secondary
    .wrapper
      small = t('.contact')
      h4 = t('.feedback')
      p  
        = t('.contact_head')
        a href=contact_path #{t('.contact_link')}
        = t('.contact_email')

app/views/search/index.html.slim
section.content-primary
  .wrapper
    - if @contents.any?
      h2 Resultado da busca
      ul.content-list
        - @contents.each do |content|
          li.content-box
            article
              h2 = link_to truncate(content.title, length: 80), [content.category, content]
              hr.waves-secondary
              p
                = truncate(content.description, length: 140)

              ul.content-actions-list
                li = link_to t('contents.index.edit'), [:edit, content.category, content] if is_admin?
                li = link_to t('contents.index.destroy'), [content.category, content], data: {:confirm => t('contents.index.confirm')}, :method => :delete if is_admin?

            .content-footer
              .attachment
                .icon = content.documents.size
              .attachment-label
                label =t('contents.index.attachments')
                = link_to t('.show'), [content.category, content]
    - else
      h2 Ooops!
      h4 = t('.search_without_content')
      hr.waves-secondary
      p
        = t('.suggestions')
        br
        = t('.send_email')
        br
        = link_to t('.back'), root_path